apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-gateway
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: spring-gateway
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/anastasiosbroadcom/spring-boot-gateway-example
      ref:
        branch: main